### PR TITLE
Setup Stylelint

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by abdonrd** [comment]
Ops! We have an error.

1. Run `npm run format:stylelint`

2. See, for example, the file `components/banner/index.ts`:

    Screenshot 2022-01-08 at 13 27 39

@43081j do you know what could be happening?

**Comment by 43081j** [comment]
hmm we did add a fix not long ago to escape backticks in mutated CSS. it must somehow be applying it to the surrounding backticks too, ill see if i can debug it this weekend 👍

**Comment by 43081j** [comment]
i think its this @abdonrd 43081j/postcss-lit#25

**Comment by 43081j** [comment]
@abdonrd can you try postcss-lit 0.4.2? it should work now

**Comment by abdonrd** [comment]
@43081j it works, thanks!

**Pull request merged**
